name: Unit Test - Project2

on: [push, pull_request]

concurrency:
  group: unit-test-lab2-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '21'
      - name: Download Junit
        id: junit
        run: |
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar
      - name: Compile
        id: javac
        run: |
          cd lab2
          javac -cp .:../junit-platform-console-standalone-1.9.3.jar:lib/beaver-ant.jar:lib/beaver-rt.jar \
            -d out \
            src/test/ParserTests.java \
            gen/lexer/Lexer.java \
            gen/parser/Parser.java
      - name: Test
        id: test
        run: |
          cd lab2
          java -jar ../junit-platform-console-standalone-1.9.3.jar \
            --class-path out:lib/beaver-ant.jar:lib/beaver-rt.jar \
            --scan-class-path
