name: Unit Test - Project4

on: [push, pull_request]

concurrency:
  group: unit-test-lab4-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '21'
      - name: Download Junit
        id: junit
        run: |
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar
      - name: Compile
        id: javac
        run: |
          cd lab4
          make compile
      - name: Test
        id: test
        run: |
          cd lab4
          make test
